version: '3'

services:
  workspace:
    build: workspace/
    depends_on:
      - db
    volumes:
      - ../:/var/www

  nginx:
    build: nginx/
    depends_on:
      - fpm
      - phpmyadmin
    volumes:
      - ../:/var/www
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "8080:80"

  fpm:
    build: fpm/
    depends_on:
      - db
    expose:
      - "9000"
    volumes:
      - ../:/var/www

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3333:80"

volumes:
    mysql:
        driver: "local"
